version: '3.7'

services:

  web:
    build: docker/
    volumes:
      - .:/data
      - ./docker/apache2.conf:/etc/apache2/conf.d/local.conf
      - ./docker/php.ini:/etc/php8/conf.d/99_docker.ini
    environment:
      VALUED_DEVELOPMENT: 'yes'
    links:
      - mariadb
    ports:
      - 26065:80

  mariadb:
    image: mariadb:10.2.44
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    ports:
      - 26066:3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false

volumes:
  mariadb:
