version: '3.7'

services:

  web:
    build: docker/
    volumes:
      - .:/data
      - ./docker/apache2.conf:/etc/apache2/conf.d/local.conf
      - ./docker/php.ini:/etc/php7/conf.d/99_docker.ini
    environment:
      VALUED_DEVELOPMENT: 'yes'
    links:
      - mariadb
    ports:
      - 26065:80

  mariadb:
    image: mariadb:10.1.45
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    ports:
      - 26066:3306


volumes:
  mariadb:
