version: '3.7'

services:

  web:
    build: docker/
    volumes:
      - .:/data
      - ./docker/apache2.conf:/etc/apache2/conf.d/local.conf
      - ./docker/php.ini:/etc/php8/conf.d/99_docker.ini
    environment:
      VALUED_DEVELOPMENT: 'yes'
    links:
      - mariadb
      - es1
    ports:
      - 26065:80

  mariadb:
    image: mariadb:10.1.45
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: magento
    ports:
      - 26066:3306

  es1:
    container_name: es1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    volumes:
        - es-data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200

volumes:
  mariadb:
  es-data:
