<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Valued\Magento2\Block\Sidebar
 */
?>
<?php if ($block->getEnabledSidebar()) { ?>
    <script>
        (function(url,id){var script=document.createElement('script');script.async=true;script.src=url+'/sidebar.js?id='+id+'&c='+cachebuster(10,id);var ref=document.getElementsByTagName('script')[0];ref.parentNode.insertBefore(script,ref);function cachebuster(refreshMinutes,id){var now=Date.now();var interval=refreshMinutes*60e3;var shift=(Math.sin(id)||0)*interval;return Math.floor((now+shift)/interval);}})('https://<?php json_encode($block->getSidebarDomain()); ?>s',<?= (int)$block->getWebshopId(); ?>);
    </script>
<?php } ?>