<?php
/**
 * Copyright © 2016 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Magmodules\WebwinkelKeur\Block\Widget\Summary
 */
?>
<div class="webwinkelkeur-big-widget">
    <?php if ($summary = $block->getSummaryData()) { ?>
        <?php if ($block->getRichSnippets()) { ?>
            <div itemscope itemtype="http://schema.org/WebPage">
                <div class="webwinkelkeur-big-score <?php echo $block->escapeHtml($summary['iso']); ?>">
                    <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                        <p>
                            <?php echo __('<span class="score">Rated with %1 </span><span class="text">Based on <a href="%2" class="webwinkelkeurPopup" title="Webshop Trustmark" target="_blank">%3 Customer Reviews</a></span>', '<span itemprop="ratingValue">' . $block->escapeHtml($summary['score']) . '</span> / <span itemprop="bestRating">' . (int)$summary['score_max'] . '</span>', $block->escapeUrl($summary['review_url']), '<span itemprop="ratingCount">' . (int)$summary['total_reviews'] . '</span>'); ?>
                        </p>
                        <div class="rating-summary">
                            <div class="rating-result">
                  	 			 <span style="width: <?php echo (int)$summary['percentage']; ?>%;"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="webwinkelkeur-big-score <?php echo $block->escapeHtml($summary['iso']); ?>">
                <p>
                    <?php echo __('<span class="score">Rated with %1 </span><span class="text">Based on <a href="%2" class="webwinkelkeurPopup" title="Webshop Trustmark" target="_blank">%3 Customer Reviews</a></span>', $block->escapeHtml($summary['score']) . ' / ' . (int)$summary['score_max'], $block->escapeUrl($summary['review_url']), (int)$summary['total_reviews']); ?>
                </p>
                <div class="rating-summary">
                    <div class="rating-result">
                  		<span style="width: <?php echo (int)$summary['percentage']; ?>%;"></span>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
</div>