<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block \Valued\Magento2\Block\Widget\Summary
 */
?>
<span id="result">
    <img class="connecting" hidden="hidden" style="margin:0 5px" src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <span id="stats_result">
        <?php if ($summaryData = $block->getReviewSummary()): ?>
            <?php foreach ($summaryData as $key => $summary): ?>
                <span class="valued-review-summary">
                    <?php if ($summary['status'] == 'success'): ?>
                        <div class="field-summary-rating">
                            <div class="rating-box">
                                <div class="rating" style="width: <?= $block->escapeHtmlAttr((int)$summary['percentage']) ?>%;"></div>
                            </div>
                        </div>
                        <?= $block->escapeHtml($summary['name']) ?><br>
                        <?= /* @noEscape */ __(
                                'Rated %1/%2 with',
                                $block->escapeHtml($summary['score']),
                        $block->escapeHtml((int) $summary['score_max'])
                    ) ?>
                        <a href="<?= $block->escapeUrl($summary['link']['default']) ?>" target="_blank"><?= /* @noEscape */  __('%1 reviews', $block->escapeHtml((int) $summary['total_reviews'])) ?></a>
                    <?php else: ?>
                        <span class="valued-review-message">
                            Website ID: <?= $block->escapeHtml($key) ?><br/>Error: <?= $block->escapeHtml($summary['msg']) ?>
                        </span>
                    <?php endif; ?>
                </span>
            <?php endforeach; ?>
        <?php endif; ?>
    </span>
</span>