<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block WebwinkelKeur\Magento2\Block\Adminhtml\Magmodules\Header
 */
?>
<div class="mm-block-webwinkelkeur" style="background-image: url(<?php echo $block->escapeUrl($block->getImage()); ?>)">
    <a class="helpbutton" href="<?php echo $block->escapeUrl($block->getSupportLink()); ?>" target="_blank">
        Manual & Support
    </a>
    <p>
        <strong>Developed by WebwinkelKeur.</strong>
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="icon2"></div>
                    <a href="https://webwinkelkeur.nl/" target="_blank">WebwinkelKeur</a>
                </td>
                <td>
                    <div class="icon1"></div>
                    <a href="<?php echo $block->escapeUrl($block->getContactLink()); ?>" target="_blank">Contact</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
